import { app, BrowserWindow, ipcMain, screen } from 'electron';
import * as readline from 'node:readline';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

type OverlayCommand = 'indicate' | 'hideAll' | 'ping';
type OverlayEvent = 'ready' | 'error' | 'interaction';

type Envelope = {
  protocolVersion: number;
  payload: Record<string, unknown>;
};

type CommandEnvelope = Envelope & { command: OverlayCommand };
type EventEnvelope = Envelope & { event: OverlayEvent };

const PROTOCOL_VERSION = 1;
let mainWindow: BrowserWindow | null = null;
let rendererReady = false;
const pendingCommands: CommandEnvelope[] = [];

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  const virtualBounds = screen.getAllDisplays().reduce(
    (acc, display) => ({
      x: Math.min(acc.x, display.bounds.x),
      y: Math.min(acc.y, display.bounds.y),
      right: Math.max(acc.right, display.bounds.x + display.bounds.width),
      bottom: Math.max(acc.bottom, display.bounds.y + display.bounds.height),
    }),
    {
      x: Number.POSITIVE_INFINITY,
      y: Number.POSITIVE_INFINITY,
      right: Number.NEGATIVE_INFINITY,
      bottom: Number.NEGATIVE_INFINITY,
    },
  );

  mainWindow = new BrowserWindow({
    x: virtualBounds.x,
    y: virtualBounds.y,
    width: virtualBounds.right - virtualBounds.x,
    height: virtualBounds.bottom - virtualBounds.y,
    transparent: true,
    frame: false,
    hasShadow: false,
    skipTaskbar: true,
    alwaysOnTop: true,
    focusable: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });
  mainWindow.setAlwaysOnTop(true, 'screen-saver');
  mainWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  mainWindow.setIgnoreMouseEvents(true, { forward: true });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.on('closed', () => {
    mainWindow = null;
  });
};

const writeEventToStdout = (event: EventEnvelope): void => {
  process.stdout.write(`${JSON.stringify(event)}\n`);
};

const sendErrorEvent = (message: string): void => {
  writeEventToStdout({
    protocolVersion: PROTOCOL_VERSION,
    event: 'error',
    payload: { message },
  });
};

const validateCommandEnvelope = (value: unknown): CommandEnvelope => {
  if (!value || typeof value !== 'object') {
    throw new Error('Command must be an object.');
  }
  const candidate = value as Record<string, unknown>;
  if (candidate.protocolVersion !== PROTOCOL_VERSION) {
    throw new Error('Unsupported protocolVersion.');
  }
  if (typeof candidate.command !== 'string') {
    throw new Error('Command field is required.');
  }
  if (!['indicate', 'hideAll', 'ping'].includes(candidate.command)) {
    throw new Error(`Unsupported command: ${String(candidate.command)}.`);
  }
  if (candidate.payload !== undefined && typeof candidate.payload !== 'object') {
    throw new Error('Payload must be an object.');
  }
  return {
    protocolVersion: PROTOCOL_VERSION,
    command: candidate.command as OverlayCommand,
    payload: (candidate.payload as Record<string, unknown>) ?? {},
  };
};

const dispatchToRenderer = (command: CommandEnvelope): void => {
  if (!mainWindow || mainWindow.isDestroyed()) {
    throw new Error('Overlay window is not available.');
  }
  if (!rendererReady) {
    pendingCommands.push(command);
    return;
  }
  mainWindow.webContents.send('overlay:command', command);
};

const flushPending = (): void => {
  if (!mainWindow || mainWindow.isDestroyed() || !rendererReady) {
    return;
  }
  while (pendingCommands.length > 0) {
    const command = pendingCommands.shift();
    if (!command) {
      break;
    }
    mainWindow.webContents.send('overlay:command', command);
  }
};

const wireStdio = (): void => {
  const rl = readline.createInterface({
    input: process.stdin,
    terminal: false,
  });

  rl.on('line', (line: string) => {
    const trimmed = line.trim();
    if (!trimmed) {
      return;
    }
    try {
      const parsed = JSON.parse(trimmed);
      const cmd = validateCommandEnvelope(parsed);
      dispatchToRenderer(cmd);
    } catch (error) {
      sendErrorEvent(error instanceof Error ? error.message : String(error));
    }
  });
};

app.on('ready', () => {
  createWindow();
  wireStdio();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.on('overlay:event', (_evt, event: EventEnvelope) => {
  if (!event || event.protocolVersion !== PROTOCOL_VERSION || typeof event.event !== 'string') {
    sendErrorEvent('Invalid renderer event envelope.');
    return;
  }

  if (event.event === 'ready') {
    rendererReady = true;
    flushPending();
  }
  writeEventToStdout(event);
});
